#!/bin/bash
# history of branch 'master' shall not be re-written
MASTER_BRANCH="master"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "$MASTER_BRANCH" ]; then
  git checkout gh-pages
  git rebase $MASTER_BRANCH
  git checkout $MASTER_BRANCH
fi
